name: peduli_utang
description: Aplikasi mengajukan permintaan hutang pada temanmu

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.3+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Function scan and make QR Code
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  # Onboarding Screen
  introduction_screen: ^1.0.9
  # State Management
  # flutter_riverpod: ^0.5.1
  flutter_riverpod: ^0.6.0-dev+2

  # Login With Google
  google_sign_in: ^4.5.1
  # Push Firebase and Local Notification
  flutter_local_notifications: ^1.4.4+2
  firebase_messaging: ^6.0.16
  # Signature
  flutter_signature_view: ^1.1.1
  auto_size_text: ^2.1.0

  collection: ^1.14.12

  firebase_crashlytics: ^0.1.3+3
  google_nav_bar: ^2.2.0
  shared_preferences: ^0.5.8
  image_picker: ^0.6.7+4
  flutter_datetime_picker: ^1.3.8
  http: ^0.12.2
  grouped_list: ^3.3.0
  global_template:
    path: global_template

  #Mandatory Freezed Package
  freezed_annotation: ^0.11.0
  json_annotation: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.7.5
  # Mandatory Freezed Package
  build_runner: ^1.10.0
  freezed: ^0.11.4
  json_serializable: ^3.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/logo_primary.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Righteous
      fonts:
        - asset: asset/fonts/Righteous-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: VarelaRound
      fonts:
        - asset: asset/fonts/VarelaRound-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
